--
-- Initialization script for apps using MeOS Online Protocol in the backend
--

DROP DATABASE IF EXISTS mop;
CREATE DATABASE if NOT EXISTS mop;
USE mop;


CREATE TABLE if NOT EXISTS mopCompetition (
	cid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT '',
	`date` DATE NOT NULL DEFAULT '2013-11-04',
	`organizer` VARCHAR(64) NOT NULL DEFAULT '',
	`homepage` VARCHAR(128) NOT NULL DEFAULT ''
	) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;
	

CREATE TABLE if NOT EXISTS mopControl (
	cid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT ''
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopClass (
	cid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY(cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT '',
	`ord` INT NOT NULL DEFAULT 0,
	INDEX(`ord`)
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopOrganization (
	cid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT ''
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopCompetitor (
	cid INT NOT NULL,
	id INT NOT NULL,
	PRIMARY KEY (cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT '',
	`org` INT NOT NULL DEFAULT 0,
	`cls` INT NOT NULL DEFAULT 0,
	`stat` TINYINT NOT NULL DEFAULT 0,
	`st` INT NOT NULL DEFAULT 0,
	`rt` INT NOT NULL DEFAULT 0,
	`bib` INT DEFAULT NULL,
	INDEX(org), INDEX(cls), INDEX(stat, rt), INDEX(st),
	tstat TINYINT NOT NULL DEFAULT 0,	-- Total status
	it INT NOT NULL DEFAULT 0				-- Input time
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopTeam (
	`cid` INT NOT NULL,
	`id` INT NOT NULL,
	PRIMARY KEY (cid, id),
	`name` VARCHAR(64) NOT NULL DEFAULT '',
	`org` INT NOT NULL DEFAULT 0,
	`cls` INT NOT NULL DEFAULT 0,
	`stat` TINYINT NOT NULL DEFAULT 0,
	`st` INT NOT NULL DEFAULT 0,
	`rt` INT NOT NULL DEFAULT 0,
	`bib` INT DEFAULT NULL,
	INDEX(org), INDEX(cls), INDEX(stat, rt), INDEX(st)
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopTeamMember (
	`cid` INT NOT NULL,
	`id` INT NOT NULL,
	`leg` TINYINT NOT NULL,
	`ord` TINYINT NOT NULL,
	PRIMARY KEY(`cid`, `id`, `leg`, `ord`),
	`rid` INT NOT NULL DEFAULT 0
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


CREATE TABLE IF NOT EXISTS mopClassControl (
	`cid` INT NOT NULL,
	`id` INT NOT NULL,
	`leg` TINYINT NOT NULL,
	`ord` TINYINT NOT NULL,
	PRIMARY KEY(`cid`, `id`, `leg`, `ord`),
	`ctrl` INT NOT NULL DEFAULT 0,
	`distance` VARCHAR(50) DEFAULT NULL
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
	
	
CREATE TABLE if NOT EXISTS mopRadio (
	`cid` INT NOT NULL,
	`id` INT NOT NULL,
	`ctrl` INT NOT NULL,
	PRIMARY KEY(`cid`, `id`, `ctrl`),
	`rt` INT NOT NULL DEFAULT 0
	) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;